photo/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
    path('upload', login_required()(upload_post), name='upload'),
    path('me', login_required()(me), name="me"),                            path('me/', login_required()(me), name="me"),
    path('me/all', login_required()(me_all), name="me_all"),                path('me/all/', login_required()(me_all), name="me_all"),
    path('me/update', login_required()(me_update), name="me_update"),       path('me/update/', login_required()(me_update), name="me_update"),
    path('me/delete', login_required()(me_delete)),                         path('me/delete/', login_required()(me_delete)),
    path('', index, name="index")
]

server/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import routers  
from home.views import *
from about.views import *
from photo.views import *
from account.views import *


from django.conf.urls import (handler400, handler403, handler404, handler500)


handler400 = 'error_handler.views.page_not_found'
handler403 = 'error_handler.views.page_not_found'
handler404 = 'error_handler.views.page_not_found'
handler500 = 'error_handler.views.page_not_found'


router = routers.DefaultRouter()  
router.register('all', ShowPost) 
router.register('own', ShowOwnPost)
router.register('user', ShowUser)
router.register('userpost', ShowUserPost, 'UserPost')
router.register('users', ShowUsersInfo)
router.register('home',Home)
router.register('about', About)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('photo.urls')),
    path('post/api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

photo/models.py
from django.db import models
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import Thumbnail, ResizeToFit, Adjust

from account.models import User




# Create your models here.


class Post(models.Model):
    index = models.BigAutoField(primary_key=True)
    upload_time = models.DateTimeField(auto_now=True ,help_text="등록 날짜")
    user = models.ForeignKey(User, related_name='users', on_delete=models.CASCADE)
    iso = models.IntegerField(default=0)
    shutter_speed = models.CharField(max_length=10)
    aperture = models.CharField(max_length=50, default="")

    content = models.TextField()

    # photo = models.ImageField(upload_to = "photo/ori_ori/%Y/%m/%d")
    photo = ProcessedImageField(
        # source="photo",
        upload_to='photo/ori_ori/%Y/%m/%d', 
        processors=[Adjust()],
        format='JPEG'
    )
    photo_thumbnail = ProcessedImageField(
        upload_to = "photo/thum/%Y/%m/%d",
        # source="photo",
        processors=[ResizeToFit(600)],
        format='JPEG',
        options={'quality':60}
    )
    photo_show = ProcessedImageField(
        # source="photo",
        upload_to='photo/show/%Y/%m/%d', 
        processors=[ResizeToFit(1800)],
        format='JPEG'
    )
    enable = models.BooleanField(default=True)
    class Meta:
        unique_together = ('index', 'upload_time')
    

photo/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['nickname', 'username', 'first_name', 'last_name', 'email', 'image', 'image_thumbnail','me',
                    'facebook', 'instargram', 'youtube']

class UploadPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields=['iso', 'shutter_speed', 'aperture', 
                'content',]
    
class UpdatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields=['iso', 'shutter_speed', 'aperture', 'content',]
    

photo/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from rest_framework import viewsets, generics, pagination
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.contrib.auth.hashers import check_password
from .models import *
from .forms import *
from .serializers import *
from account.serializers import *
from django.views.decorators.csrf import csrf_exempt


def index(request):
	return render(request, 'index.html', {})


def upload_post(request):
	if not request.user.is_staff:
		return HttpResponse("스태프 권한이 없습니다.")
	if request.method == 'POST':
		form = UploadPostForm(request.POST, request.FILES)	
		if form.is_valid():
			upload = form.save(commit=False)
			upload.user= request.user
			upload.photo = request.FILES.dict()['photo']
			upload.photo_thumbnail = request.FILES['photo']
			upload.photo_show = request.FILES['photo']
			upload.save()
			return render(request, 'photo/upload_end.html', {})
	form = UploadPostForm()
	return render(request, 'photo/upload_post.html', {"form":form})


def me(request):
	context = {}
	if not request.method == 'POST':
		context.update({"form":UserForm})
		return render(request, "photo/editme.html", context)
	user = get_object_or_404(User, pk = request.user.id)
	if not check_password(request.POST['password'], user.password):
		context.update({"form":UserForm, "pass_error":"비밀번호가 틀렷습니다"})
	else:
		form = UserForm(request.POST, request.FILES, instance=user)
		if form.is_valid():
			update = form.save(commit=False)
			update.image_thumbnail = request.FILES.dict()['image']
			update.save()
			context.update({"sucsses":"수정 완료", "end_color":"rgb(49,170,49)"})
		else :
			context.update({"sucsses":"수정 실패", "end_color":"rgb(170,49,49)"})	
			
	user = get_object_or_404(User, pk = request.user.id)
	context.update({"form":UserForm(instance=user)})
	return render(request, "photo/editme.html", context)


def me_all(request):
	if not request.user.is_staff:
		return HttpResponse("스태프 권한이 없습니다.")
	post_list = Post.objects.all().filter(user = request.user).filter(enable=True).order_by('-index')
	return me_content(request, post_list)




def me_content(request, post_list):
	paginator = Paginator(post_list, 10)
	page = request.GET.get('page')
	contacts = paginator.get_page(page)
	return render(request, "photo/me_all.html", {'contacts':contacts})


def me_update(request):

	if not request.method == 'POST':
		return HttpResponse("응 아니야")
	index = request.POST.get('index')
	post = get_object_or_404(Post ,pk = index)
	if post.index!= int(index):
		return HttpResponse("더더욱 아니야")
	form = UpdatePostForm(request.POST, instance=post)
	if form.is_valid():
		form.save()
	return redirect('me_all')



def me_delete(request):
	index = request.GET.get('del')
	print(index)
	post = get_object_or_404(Post ,pk = index)
	if post.index!= int(index):
		return HttpResponse("너꺼 아니야")
	post.enable = False
	post.save()

	return redirect('me_all')




class ShowPostSetPagination(pagination.PageNumberPagination):
	page_size = 10
	page_size_query_param = 'page_size'
	max_page_size = 10000
	http_method_names = ['get']


class ShowPost(viewsets.ModelViewSet):
# class ShowPost(generics.ListAPIView):
	queryset = Post.objects.all().filter(enable=True).order_by('-index')
	serializer_class = PostSerializer
	pagination_class = ShowPostSetPagination
	http_method_names = ['get']
class ShowOwnPost(viewsets.ModelViewSet):
	queryset = Post.objects.all().filter(enable=True).order_by('-index')
	serializer_class = PostSerializer

	def get_queryset(self):
		id = self.request.query_params.get('id', None)
		queryset = Post.objects.all().filter(enable=True).order_by('-index')
		if id is not None:
			queryset = queryset.filter(index=id)
			return queryset
	http_method_names = ['get']


class ShowUserPost(viewsets.ModelViewSet):
	
	serializer_class = PostSerializer
	pagination_class = ShowPostSetPagination
	http_method_names = ['get']

	def get_queryset(self):
		queryset = Post.objects.all().filter(enable=True).order_by('-index')
		nickname = self.request.query_params.get('nickname', None)
		if nickname is not None:
			user = get_object_or_404(User, nickname=nickname)
			queryset = queryset.filter(user=user)
			return queryset

templates/photo/me_all.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<div class="w3-container">
{% for contact in contacts %}
        <form action="/me/update" method="post" class="w3-card-4 w3-light-grey card-option" style="
            margin:10px;
            display: inline-flex;
            width:400px;">{% csrf_token %}
            <input type="hidden" name="index" value="{{contact.index}}">
            <div class="w3-container w3-center">
                <img src="{{contact.photo_thumbnail.url}}" alt="Avatar" style="width:80%; margin-top:20px;">
                <h4><textarea id="content" name="content">{{contact.content}}</textarea></h4>
                <h5>ISO <input class="detail" type="number" value="{{contact.iso}}" name="iso">|
                    <input class="detail" type="text" value="{{contact.aperture}}" name="aperture">|
                    <input class="detail" type="text" value="{{contact.shutter_speed}}" name="shutter_speed"></h5>
                <input type="submit" class="w3-button w3-green" value="수정하기" style="width:150px;">
                <a href="/me/delete/?del={{contact.index}}">
                    <input class="w3-button w3-red" value="삭제하기" style="width:120px;"/>
                </a>
            </div>
        </form>    
{% endfor %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if contacts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ contacts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
        </span>

        {% if contacts.has_next %}
            <a href="?page={{ contacts.next_page_number }}">next</a>
            <a href="?page={{ contacts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
<style>
        .detail{
            width:80px;
            font-size: 1em;
        }
        .pagination{
            text-align: center;
        }
</style>


{% endblock %}

templates/photo/upload_end.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <h1 style="text-align:center;">업로드 완료</h1>
{% endblock %}

templates/photo/upload_post.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<form method="post" action="/upload" enctype="multipart/form-data">{% csrf_token %}
    <p><label for="id_iso">ISO:</label> <input type="number" name="iso" value="0" required="" id="id_iso"></p>
    <p><label for="id_shutter_speed">셔터스피드:</label> <input type="text" name="shutter_speed" maxlength="10" required="" id="id_shutter_speed"></p>
    <p><label for="id_aperture">조리개:</label> <input type="text" name="aperture" maxlength="50" required="" id="id_aperture"></p>
    <p><label for="id_content">내용:</label> <textarea name="content" cols="40" rows="10" required="" id="id_content" style="margin: 0px; height: 168px; width: 307px;"></textarea></p>
    <p><label for="id_photo">사진:</label> <input type="file" name="photo" accept="image/*" required="" id="id_photo"></p>
    <p><input type="submit" value="등록하기"></p>
</form>
{% endblock %}